version: '2'
services:
    hibernate-postgresql:
        container_name: hibernate-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/hibernate/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=hibernate
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
